[
  { text: "Great Scott! One bite of this Brazilly Philly and I hit 88mph with flavor. The flux capacitor’s got competition!",
    author: "🧑‍🔬 Doc Brown, Back to the Future Magazine" },
  { text: "I came back in time… for this sandwich. I’ll be back. With guaraná.",
    author: "🤖 T-800, The Terminator Magazine" },
  { text: "We stole gold from Napoleon, but THIS? This sandwich is the real treasure of the multiverse.",
    author: "🧝‍♂️ Randall, Time Bandits Quarterly" },
  { text: "I traversed epochs in search of enlightenment. Then I tasted this sandwich. My journey is complete.",
    author: "🎩 H.G. Wells’ Time Traveler, The Time Machine Digest" },
  { text: "I built a box to cheat time… turns out I just needed to cheat lunch. Brazilly Philly rewires your taste timeline.",
    author: "🧠 Abe, Primer Circular" },
  { text: "It’s me, serving myself, the same sandwich, at every moment in time. I’m all the customers. And it’s always worth it.",
    author: "🌀 Agent, Predestination Monthly" },
  { text: "28 days… 6 hours… 42 minutes… 12 seconds… until you taste true destiny: the Brazilly Philly.",
    author: "🐇 Frank the Rabbit, Donnie Darko Magazine" },
  { text: "In every version of reality, the sandwich slaps. The universe converged to make this one thing consistent.",
    author: "🚪 Everyone in that house, Coherence Journal" },
  { text: "I ate it forwards, then inverted and tasted it backwards. Still incredible. Sandwich entropy is real.",
    author: "🔄 The Protagonist, Tenet Review Weekly" },
  { text: "Love isn’t the only thing that transcends dimensions… apparently provolone does too.",
    author: "🌌 Cooper, Interstellar Culinary Digest" },
  { text: "I made some bad choices. But eating this sandwich wasn’t one of them.",
    author: "👨‍🦲 Héctor, Timecrimes Review" },
  { text: "BRAZILLY PHILLY IS MOST EXCELLENT, DUDE!",
    author: "🎸 Bill & Ted, Wyld Stallyns Magazine" },
  { text: "I went back to the '80s and tried everything. This sandwich still wins. It’s got the meats and the moves.",
    author: "🧖 Lou, Hot Tub Time Machine Monthly" },
  { text: "Day 6,434. Still not tired of the Brazilly Philly. I dream of provolone.",
    author: "⏰ Phil, Groundhog Day Digest" },
  { text: "Time loop? More like taste loop. I eat this every day. I’m not even mad.",
    author: "🌴 Nyles, Palm Springs Weekly" },
  { text: "This sandwich might be a fixed point in time. You literally can't screw it up. Unless you forget the vinagrete.",
    author: "🍻 Ray, FAQ About Time Travel Magazine" },
  { text: "Yeah baby, this sandwich is shagadelic! Spicy, cheesy, and oh behave!",
    author: "🕶️ Austin, Shagadelic Eats Quarterly" },
  { text: "I fell through time and landed mouth-first into this Brazilly Philly. That’s divine intervention, playa.",
    author: "🛡️ Jamal Walker, Black Knight Bites" },
  { text: "Live. Die. Eat Brazilly Philly. Repeat.",
    author: "💥 Cage, Edge of Tomorrow Chronicle" },
  { text: "I tried to shoot my future self… but he had this sandwich. We made peace. It’s that good.",
    author: "🪞 Joe, Looper Digest" },
  { text: "I’ve been through wars, time jumps, and heartbreak. This sandwich healed my soul faster than my skin.",
    author: "🧬 Wolverine, Mutant Flavor Times" },
  { text: "Part of the sandwich stays with you. Like a flavor stone. I love you 3000 calories.",
    author: "🛡️ Tony Stark, Endgame Culinary Report" },
  { text: "I keep tasting this for the first time… again. Some flavors ripple through time.",
    author: "🕵️ Doug Carlin, Déjà Vu Digest" },
  { text: "If you see a red door and smell grilled picanha, go in. That’s your sign from the future.",
    author: "🐒 James Cole, 12 Monkeys Weekly" },
  { text: "We went back to change the past. But even there, Brazilly Philly was king. Time-proof.",
    author: "📹 David, Project Almanac Times" },
  { text: "We’re stuck in a time loop, but with sandwiches like this? Who cares.",
    author: "🔁 Ren, ARQ Circular" },
  { text: "Eight minutes to save the world? Fine. But first, let me finish this Brazilly Philly.",
    author: "🚆 Colter Stevens, Source Code Review" },
  { text: "I saw this sandwich coming two minutes early. And I STILL wasn’t ready.",
    author: "🧠 Cris Johnson, Next Digest" },
  { text: "I may vanish at any moment… but please save me a bite. The love I have for this sandwich is timeless.",
    author: "💔 Henry, The Time Traveler’s Wife Weekly" },
  { text: "I could relive any moment. I keep choosing the one where I first taste Brazilly Philly.",
    author: "🎀 Tim, About Time Digest" },
  { text: "The past called. It wants the sandwich too.",
    author: "⌛ Richard Collier, Somewhere in Time Magazine" },
  { text: "In my era, cuisine was honorable. But this? This sandwich is a revelation of modern flavor.",
    author: "🎩 Leopold, Kate & Leopold Review" },
  { text: "Even across time, bodies, and space… our souls are linked by one craving: Brazilly Philly.",
    author: "🌠 Taki, Your Name Journal" },
  { text: "I tried to fix the past. But the only constant was this sandwich changing my fate.",
    author: "🦋 Evan, Butterfly Effect Digest" },
  { text: "Reality warps. Time folds. But this sandwich… it centers me.",
    author: "🧥 Jack Starks, The Jacket Quarterly" },
  { text: "I keep making the same mistake… not ordering two.",
    author: "⛴️ Jess, Triangle Magazine" },
  { text: "This is not a joke. I tasted the Brazilly Philly before anyone else. I built the machine for another bite.",
    author: "📨 Kenneth, Safety Not Guaranteed Circular" },
  { text: "Infinite versions of me all agree: this sandwich defines the perfect timeline.",
    author: "∞ Dean, The Infinite Man Journal" },
  { text: "I tried to rewrite the past. But once I had a Brazilly Philly, the future finally made sense.",
    author: "🇧🇷 João “Zero”, The Man from the Future Quarterly" },
  { text: "First I saved the world, then I discovered the Brazilly Philly. Honestly, the sandwich is harder to beat.",
    author: "🕹️ Josh Futturman, Future Man Magazine" },
  { text: "The beginning is the end. The end is the beginning. But the sandwich? The sandwich is perfect.",
    author: "🌌 Jonas, Dark (Netflix) Magazine" },
  { text: "We came from the future to save humanity… and then stayed for lunch.",
    author: "🕶️ Marcy, Travelers Journal" },
  { text: "Every chapter of history improved after introducing this sandwich. Even 18th century France.",
    author: "⏳ Lucy Preston, Timeless Review" },
  { text: "All of time and space… anywhere and everywhere. I choose the Brazilly Philly.",
    author: "🚀 The Doctor, Doctor Who Magazine" },
  { text: "Jamie can have the whiskey. I’ll take this sandwich. It transcends centuries.",
    author: "🏴‍☠️ Claire Fraser, Outlander Times" },
  { text: "Oh boy… this sandwich is leaps ahead of its time.",
    author: "🔮 Sam Beckett, Quantum Leap Weekly" }
]
